### ISSUE TITLE
Feedback and Note taking example

### ISSUE THREAD

**Issue by brandonbrown** [TraceLarson/HouseFax#4]
Hi Trace,

As part of the Capstone Project, you'll be receiving feedback and direction from different people- sometimes on the same topic. To help avoid potential conflicting direction or spending too much time on a single area of review, we would like you to create issues using the "meeting" label describing the interactions you have with instructors. 

What we would like to see, is a general issue such as this, with a plain text overview of what the interaction was like (such as the paragraph above) with a small list of action items. This list, once reviewed by the instructor you interacted with for accuracy, will then be broken out into classic issues that can be tracked and acted upon as normal. For example:

- Record any interaction with instructors as a Meeting issue
- Create Action Items from the meeting
- Ping or assign instructor to issue
- Upon review, create individual issues from action items

**Comment by brandonbrown** [comment]
Instructors and anyone collaborating with the project can offer feedback on the issue. This way we can ensure communication is clear and you're not being pushed in different directions. Once the action items have been created from this issue, the meeting issue may be closed. If you have any questions about this feel free to ping anyone on the Capstone team.

**Comment by TraceLarson** [comment]
An overview of the conversation I had with Chapman about this workflow. From this meeting comments are added that will encompass outside conversations with team members and professors. Tagging of the outside person is suggested so that you can bring them into the conversation. If the initial meeting demands it or if during the discussion Issues need to be created they should be linked to using '#', this is to let future you know that the issue was not abandoned. After all criteria for this discussion have been addressed/solved the meeting can be closed.
